### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by 0x1mason** [soho737/NGribCS#1]
I'm working on a .NET app that needs Grib support. I might be willing to contribute to this project. Can you provide any further specifics on what your plans are?

**Comment by soho737** [comment]
Hi! I would be glad if you would like to contribute!

I had to relocate my office on short notice and my infrastructure is still not properly set up. I'll get back to you as soon as everything is back in working condition (maybe 4 weeks).

The code is already in an "almost usable" state for reading GRIB2 files, so if you need a quick solution just let me know and I give you some guidance how to use it.

**Comment by 0x1mason** [comment]
No rush. I'll check back. Thanks.

**Comment by 0x1mason** [comment]
Feel free to ping me in this thread.

**Comment by 0x1mason** [comment]
Hello @soho737. I ended up writing [GribApi.NET](https://github.com/0x1mason/GribApi.NET), a wrapper for grib_api. It supports reading and writing GRIB 1 and 2 files. I'd love any feedback or suggestions you have to offer. Thanks.
